---
abstract: 'Mix-in inheritance, an alternative to multiple inheritance'
author:
  - 'Michael G Schwern E<lt>schwern@pobox.comE<gt>'
build_requires:
  Test::More: '0.4'
  Test::NoWarnings: '0'
configure_requires:
  Module::Build: '0.36'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
keywords:
  - mixin
  - inheritance
  - devel
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: mixin
provides:
  mixin:
    file: lib/mixin.pm
    version: '0.09'
  mixin::with:
    file: lib/mixin/with.pm
    version: '0.09'
requires:
  base: '0'
resources:
  bugtracker: https://github.com/shlomif/mixin/issues
  homepage: https://github.com/shlomif/mixin
  license: http://dev.perl.org/licenses/
  repository: https://github.com/shlomif/mixin
version: '0.09'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
